config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'toppage#index'
  namespace :posts do
    resources :searches, only: :index
  end
  
  resources :relationships, only: %i[create destroy]
  resources :maps, only: %i[index]
  get '/map_request', to: 'maps#map', as: 'map_request'
  resources :users, only: %i[show]
  resources :posts do
    resources :comments, only: %i[create destroy]
  end

  post   '/like/:post_id' => 'likes#like',   as: 'like'
  delete '/like/:post_id' => 'likes#unlike', as: 'unlike'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post, counter_cache: :likes_count
end

app/models/post.rb
class Post < ApplicationRecord
  # before_save :geocode_full_address
  belongs_to :user
  geocoded_by :title
  after_validation :geocode
  acts_as_taggable
  validates :title,:image,:description, presence: true
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user
  has_many :comments

  def self.search(search)
    if search
      Post.where('title LIKE(?) OR description LIKE (?)', "%#{search}%", "%#{search}%").order("created_at DESC")
    else
      Post.all
    end
  end

  # def geocode_full_address
  #   coords = Geocoder.coordinates(
  #     self.prefecture + self.city + self.address # 県名 + 市町村名 + 丁目番地
  #   )
  #   self.latitude = coords[0]
  #   self.longitude = coords[1]
  # end

  mount_uploader :image, ImageUploader
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post
  has_many :comments

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?


  def create_google_map_marker
    @hash = Gmaps4rails.build_markers(@posts) do |post, marker|
    marker.lat post.latitude
    marker.lng post.longitude
    marker.infowindow post.title
    marker.infowindow render_to_string(partial: 'shared/infowindow', locals: { post: post })
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # before_action :set_post

  def create
    @comment = Comment.create(content: comment_params[:content], post_id: comment_params[:post_id], user_id: current_user.id)
    @post = Post.find(params[:post_id])
    # if @comment.save
    #   redirect_to root_path
    # else
    #   @posts = @post.comments.includes(:user)
    #   flash.now[:alert] = 'メッセージを入力してください。'
    #   render root_path
    # end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_variables

  def like
    like = current_user.likes.new(post_id: @post.id)
    like.save
  end

  def unlike
    like = current_user.likes.find_by(post_id: @post.id)
    like.destroy
  end

  private

  def set_variables
    @post = Post.find(params[:post_id])
    @id_name = "#like-link-#{@post.id}"
    @id_heart = "#heart-#{@post.id}"
  end

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
    @posts = Post.all
    create_google_map_marker
  end

  def map
    results = Geocoder.search(params[:address])
    @latlng = results.first.coordinates
    # これでmap.js.erbで、経度緯度情報が入った@latlngを使える。
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/posts/searches_controller.rb
class Posts::SearchesController < ApplicationController
  def index
    @posts = Post.search(params[:keyword])
    respond_to do |format|
      format.html
      format.json
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :show]


  def index
    @posts = Post.all.order("created_at DESC").page(params[:page]).per(9)
    if params[:tag_name]
      @posts = @posts.tagged_with("#{params[:tag_name]}").order("created_at DESC")
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    if @post.save
      redirect_to maps_path
    else
      redirect_to new_post_path
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
  end

  def edit
    
  end

  def update

  end

  def destroy

  end


  private

  def set_post
    @comment = Comment.new
    @post = Post.find(params[:id])
    @comments = @post.comments
  end

  def post_params
    params.require(:post).permit(:title,:description,:image, :tag_list).merge(user_id: current_user.id)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :set_user

  def create
    user = User.find(params[:relationship][:follow_id])
    following = current_user.follow(user)
    if following.save
      flash[:success] = 'ユーザーをフォローしました'
      redirect_to user
    else
      flash.now[:alert] = 'ユーザーのフォローに失敗しました'
      redirect_to user
    end
  end

  def destroy
    user = User.find(params[:relationship][:follow_id])
    following = current_user.unfollow(user)
    if following.destroy
      flash[:success] = 'ユーザーのフォローを解除しました'
      redirect_to user
    else
      flash.now[:alert] = 'ユーザーのフォロー解除に失敗しました'
      redirect_to user
    end
  end

  private

  def set_user
    user = User.find(params[:relationship][:follow_id])
  end
  
end

app/controllers/toppage_controller.rb
class ToppageController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(5).order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user?(user)
    user == current_user
  end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/comments/_comment.html.haml
= comment.content

app/views/comments/_count.haml
= post.comments.count

app/views/comments/_form.html.haml
= form_for([post, comment], method: :post,  remote: true  ) do |f|
  = f.text_field :content, placeholder: "コメントを残す（100字以内）", class: "post-comment",rows: "1"
  = f.submit class: "dn"

app/views/comments/create.js.haml
$("#comments_area").append("#{j(render 'comments/comment', comment: @comment)}")
-# $("#flash-con").html("<%= j(render 'layouts/flash') %>")
$(".count").html("#{j(render 'comments/count', post: @post )}");
-# $("#comment-error").html("<%= j(render 'layouts/error_message', object: @comment) %>")
$("#comment_content").val('')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Superd_view
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    %script{:src => "//maps.google.com/maps/api/js?key=#{Rails.application.credentials[:GOOGLE_MAP_KEY]}"}
    %script{:src => "//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"}

  %body
  .navbar
    .navbar__logo
      = link_to "SuperdView", root_path
    .navbar__menu
      %ul.navbar__menu
        - if user_signed_in?
          %li.navbar__menu--item
            = link_to current_user.name, user_path(current_user.id)
          %li.navbar__menu--item
            = link_to "投稿一覧", posts_path
          %li.navbar__menu--item
            = link_to "世界地図", maps_path
          %li.navbar__menu--item
            = link_to "新規投稿", new_post_path
          %li.navbar__menu--item
            = link_to "ログアウト", destroy_user_session_path, method: :delete
        - else
          %li.navbar__menu--item
            = link_to "新規登録", new_user_registration_path
          %li.navbar__menu--item
            = link_to "ログイン", new_user_session_path
            = Rails.application.credentials[:GOOGLE_MAP_KEY]
  = yield
  #modal-container

app/views/likes/_like_links.html.haml
%div.like-link{id: "like-link-#{post.id}"}
  - if current_user.likes.find_by(post_id: post.id)
    = link_to unlike_path(post.id), method: :delete, remote: true do
      .btn.btn-default.glyphicon.glyphicon-heart{id: "heart-#{post.id}"}
        = post.likes.count.to_s
  - else
    = link_to like_path(post.id), method: :post, remote: true do
      .btn.btn-default.glyphicon.glyphicon-heart-empty{id: "heart-#{post.id}"}
        = post.likes.count.to_s

app/views/likes/like.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like_links", post: @post  )) %>');
$("<%= @id_heart %>").removeClass('glyphicon-heart-empty');
$("<%= @id_heart %>").addClass('glyphicon-heart');

app/views/likes/unlike.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like_links", post: @post  )) %>');
$("<%= @id_heart %>").addClass('glyphicon-heart-empty');
$("<%= @id_heart %>").removeClass('glyphicon-heart');

app/views/maps/index.html.haml
%div{:style => "width: 100%;"}
  #map{:style => "width: 100%; height: 100vh;"}

:javascript
  handler = Gmaps.build('Google');
  handler.buildMap({ 
    provider: {mapTypeId: 'hybrid'},
    internal: {id: 'map'}
    }, 
    function(){
    markers = handler.addMarkers(#{raw @hash.to_json})
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setCenter(new google.maps.LatLng(35.681298, 139.7640582));
    handler.getMap().setZoom(4);
  });

app/views/posts/_post.html.haml
.card
  - @posts.each do |post|
    = link_to(post, class: "post-link", remote: true) do
      .card__contant
        .card__contant-title
          = post.title
        .card__contant-main
          .card__contant-main-image
            = image_tag post.image.url, class: "post_photo"
          .card__contant-main-description
            = post.description
          - post.tag_list.each do |tag|
            = link_to tag, posts_path(tag_name: tag), class: "text-white"
          = link_to post.user.name, user_path(post.user.id)
          = render 'likes/like_links', post: post

app/views/posts/_show.html.haml
#modal.modal-dialog
  .modal-content
    .post-show-container.container
      #close.close-btn
        .batsu
      - if  current_user?(@post.user)
        .edit-btn
          .edit-btn__v
          %ul.edit-btn__list
            -# %li.edit-btn__list__item= link_to "編集", edit_post_path(@post)
            -# %li.edit-btn__list__item= link_to "投稿を削除する",                                                                              |
              -# = post_path(@post, post_id: @post.id), method: "delete", remote: true, data: {confirm: "削除しますか？"} |
      %h2
        = @post.title
        = image_tag @post.image.url
        = @post.description
        - @post.tag_list.each do |tag|
          = link_to tag, posts_path(tag_name: tag), class: "text-white"
        = @post.user.name
        #map{:style => "width: 50%; height: 50vh;"}
        -# .form
        -#   = form_for [@post, @comment] do |f|
        -#     = f.text_field :content, class: 'form__message', placeholder: 'type a message'
        -#     = f.submit 'Send', class: 'form__submit'
        .comment-box
          = render 'comments/form', comment: @comment, post: @post
        #comments_area
          = render partial: 'comments/comment', collection: @comments
        %span.comment_count.count
          = render 'comments/count', post: @post
      -# .picture-con
      -#   - @post.pictures.each do |picture|
      -#     = image_tag picture.url, class:"post-picture"
      -# #map{:style => "width: 100%; height: 500px;"}
      -# .post-footer
      -#   .post-footer__content
      -#     .post-user
      -#       = image_tag @post.user.profile_image.url, class: "profile-image", size:"100"
      -#       .post-user__profie
      -#         = link_to @post.user.name, @post.user
      -#         = render 'users/follow_form', user: @post.user
      -#     .post-description
      -#       %span= created_date(@post)
      -#       = simple_format(@post.description)
      -#     .post-activity
      -#       %ul.activity-list
      -#         %li.activity-list__item
      -#           = image_tag 'comment.svg', class: "comment-icon"
      -#           %span.comment_count
      -#             = render 'comments/count', post: @post
      -#         %li.activity-list__item.lav
      -#           %span#like_form
      -#             = render'likes/like_form', post: @post
      -#           %span.like_count
      -#             = render 'likes/like_count', post: @post
      -#           %span#like_list
      -#             = render "likes/like_list", post: @post
      -#         %li.activity-list__item.lav
      -#           = image_tag 'eye.svg', class: "eye-icon"
      -#           = @post.footprints.count
      -#           %ul.lav-lavel
      -#             - @post.footprint_users.each do |user|
      -#               %li.lav-lavel__list
      -#                 %span
      -#                   = link_to(user, class: "lav-lavel__list--link") do
      -#                     = image_tag user.profile_image.url, class: "profile-image", size: "25"
      -#                     %span.user-name= user.name
      -#     .post-tags
      -#       %h4 タグ一覧
      -#       .post-tags__con
      -#         - @post.tag_list.each do |tag|
      -#           = link_to tag,posts_path(tag_name: tag), class: "post-tags__link"
      -#   .post-footer__content
      -#     .post-footer__content__comment
      -#       .comment-box
      -#         - if user_signed_in?
      -#           = image_tag current_user.profile_image.url, class: "profile-image", size: "80"
      -#           = render 'comments/form', comment: @comment, post: @post
      -#         - else
      -#           .request-login
      -#             = link_to "ログインしてコメントを残す。", user_session_path , |
      -#               class: "request-login__link"                  |
      -#       #comment-error
      -#         = render 'layouts/error_message', object: @comment
      -#         = render partial: 'comments/comment', collection: @comments
-# = javascript_include_tag('post_close')

:javascript
  handler = Gmaps.build('Google');
  handler.buildMap({ 
    provider: {mapTypeId: 'hybrid'},
    internal: {id: 'map'}
    }, 
    function(){
    markers = handler.addMarkers([
      {
        "lat":  #{@post.latitude.to_json},
        "lng":  #{@post.longitude.to_json},
      }
    ])
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    handler.getMap().setCenter(new google.maps.LatLng(35.681298, 139.7640582));
    handler.getMap().setZoom(4);
  });

app/views/posts/index.html.haml
= form_with(url: posts_searches_path, local: true, method: :get, class: "search-form") do |form|
  = form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input"
  = form.submit "検索", class: "search-btn"
.postspage
  .postspage__main
    投稿一覧
  .postspage__content
    = render partial: "post"
= paginate(@posts)

app/views/posts/new.html.haml
.formpage
  = form_with model: @post ,local: true do |f|
    .formpage_content
      .formpage_content__title
        タイトル
        %br
        = f.text_field :title
      .formpage_content__title
        画像投稿
        %br
        %label
          .image-file
            ファイルを選択
            = f.file_field :image, class: 'hidden'
      .formpage_content__description
        説明
        %br
        = f.text_area :description
      -#  #タグ入力フォームを追加
      .form-group 
        = f.label 'タグ'
        %br
        = f.text_field :tag_list, value: @post.tag_list.join(','), class: "form-control"
      .formpage_content__btn
        = f.submit '投稿する'

app/views/posts/searches/index.html.haml
= form_with(url: posts_searches_path, local: true, method: :get, class: "search-form") do |form|
  = form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input"
  = form.submit "検索", class: "search-btn"
.postspage
  .postspage__main
    投稿一覧
  .postspage__content
    = render partial: "posts/post"

app/views/posts/show.js.erb
$("#modal-container").html("<%= escape_javascript(render 'show') %>")
$(".modal-dialog").show();
$('body').css('overflow','hidden');

app/views/posts/show.js.haml
$("#modal-container").html("#{escape_javascript(render 'show')}")
$(".modal-dialog").show();
$('body').css('overflow','hidden');

app/views/relationships/_follow_button.html.haml
- unless current_user == user
  - if current_user.following?(user)
    = form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f|
      = f.hidden_field :follow_id, value: user.id
      = f.submit 'フォロー中', class: 'follow-now'
  - else
    = form_for(current_user.relationships.build) do |f|
      = f.hidden_field :follow_id, value: user.id
      = f.submit 'フォロー', class: 'follows'

app/views/shared/_infowindow.html.haml
= post.title
= image_tag post.image.url, class: 'infowindow-img-top'
= post.description
= link_to "マップを開く" ,"https://maps.google.co.jp/maps?q=loc:#{post.latitude},#{post.longitude}&iwloc=J",target: "_blank"

app/views/toppage/index.html.haml
.toppage
  .toppage__content
    .toppage__content--title
      SUPERD　VIEW
    .toppage__content--main
      SUPEDVIEW
      %br/
      それは絶景という意味です。
      %br/
      みんなで世界中の絶景を投稿しましょう！
    .toppage__content--btn
      - unless current_user
        = link_to "会員登録", new_user_registration_path
        = link_to "ログイン", new_user_session_path

app/views/users/show.html.haml
.postspage
  .postspage__main
    - if current_user.id == @user.id
      自分の投稿
    - else
      #{@user.name}さんの投稿
  = render "relationships/follow_button", {user: @user}
  .postspage__content
    = render partial: "posts/post"